### ISSUE TITLE
link list file is broken

### ISSUE THREAD

**Issue by orweiser-code** [facebookresearch/co3d#23]
Hey - the link list file that we should get at the bottom of this page:
[https://ai.facebook.com/datasets/co3d-downloads/](https://ai.facebook.com/datasets/co3d-downloads/)
is broken - it shows only one link to one dataset (apples)

**Comment by davnov134** [comment]
Hi, sorry for the inconvenience, we are investigating.

**Comment by w-hc** [comment]
hi David @davnov134 many of the links from "Download all links" have their URL signatures expired. Does this have to do with the webpage https://ai.facebook.com/datasets/co3d-downloads/ not updating itself properly? Thanks

**Comment by davnov134** [comment]
Yes, unfortunately there seems to be an issue with the site. We have a team investigating the issue, they did put it on top of their priority list. Thanks ahead for the patience with this. Should be fixed soon.

**Comment by davnov134** [comment]
We just got a message from our maintenance team that the links have been fixed. Can you please config @w-hc , @orweiser-code ?

**Comment by orweiser-code** [comment]
nope... checked with 2 different browsers... link still shows only the apple link

**Comment by w-hc** [comment]
Seems to work for me now.

**Comment by orweiser-code** [comment]
@w-hc what exactly is working for you? the download links themselves or the link to the object urls?
for me only the download links themselves work, but the link to the url list routes me to a page with only one url - the apple set

**Comment by w-hc** [comment]
@orweiser-code I am outside and only have my phone. The links on the webpage are populated. I haven’t tried downloading. Will update u guys when I get back.

**Comment by w-hc** [comment]
@davnov134 @orweiser-code 
There are 2 problems:
1. the URLs in "Download all links" are still stale. URLs to "chair", "hairdryer", etc have expired. 
2. on the main page, there are only 46 categories, and their links seems to work (I've only tested a few). Orange,  Teddybear, toaster, toilet, toybus are missing.

**Comment by w-hc** [comment]
Of the categories on the main "mouse click" download page, the link to bottle.zip always fails at 3.7G (out of 10.1G). I tried it twice. Other 45 categories are fine and their checksums match.

**Comment by davnov134** [comment]
Hi, we got a message from our infra team that the dataset is now available in full. Thanks for your patience.
